Repository AY2425S1-CS2103T-T15-4/tp, pull requests merged in 2024-10, with the labels that each got.

#22 Add Ze Hao's portfolio markdown file
  docs/team/leezehao.md
Labels: type.Task

#23 Add Ze Hao's photo
  docs/images/leezehao.png
Labels: type.Task

#27 Add Ren Yick's photo
  docs/images/itsmenengyi.png
Labels: type.Task

#31 Add giahien's photo
  docs/images/mrnobody0505.png
Labels: type.Task

#38 Add Project data structure and storage support
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/project/Id.java
  src/main/java/seedu/address/model/project/Name.java
  src/main/java/seedu/address/model/project/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/main/java/seedu/address/model/project/exceptions/DuplicateProjectException.java
  src/main/java/seedu/address/model/project/exceptions/ProjectNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/project/IdTest.java
  src/test/java/seedu/address/model/project/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/project/NameTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: type.Story, priority.High

#45 Fix Project(s) not loading from JSON on app startup
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/project/UniqueProjectList.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug, priority.High, severity.High

#50 Filter skills
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/skill/SkillsContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/skill/SkillTest.java
  src/test/java/seedu/address/model/skill/SkillsContainsKeywordsPredicateTest.java
Labels: type.Story, priority.High

#59 Update add and edit commands for employee id and skills
  docs/UserGuide.md
Labels: type.Task

#62 Specify tags skills usage
  docs/UserGuide.md
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, severity.VeryLow

#66 Modify ui to show project id on project card
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProjectListCard.fxml
Labels: type.Task, priority.High

#69 Implement storage of Assignments
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAssignmentsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Task, priority.High

#74 Update employee command usage messages
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, severity.VeryLow

#72 Add `listprojectmembers` command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/ListProjectMembersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListProjectMembersCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/AssignmentProjectPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/ui/AssignmentCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/model/assignment/UniqueAssignmentListTest.java
  src/test/java/seedu/address/testutil/AssignmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
Labels: type.Task

#79 Fix bug in listprojectmembers
  src/main/java/seedu/address/logic/commands/ListProjectMembersCommand.java
Labels: type.Bug, priority.High

#83 Update version for v1.3
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#85 Fix toModelType_typicalAssignmentsFile_success test not passing
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalAssignments.java
Labels: type.Bug

#96 Enable assertions in build.gradle
  build.gradle
Labels: type.Task, priority.High

#94 Update person uml
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Task

#107 Add `listprojectmembers` tests
  src/main/java/seedu/address/logic/commands/ListProjectMembersCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListProjectMembersCommandTest.java
  src/test/java/seedu/address/logic/parser/ListProjectMembersCommandParserTest.java
Labels: type.Task, priority.Medium

#102 Fix tests for AssignCommand not working
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Labels: type.Bug, severity.Medium

#106 Update Model Component UML Diagrams in DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#111 Fix assignment Id format exception error not shown to user bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High, severity.Medium

#101 Improve defensiveness person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/EmployeeId.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/skill/SkillsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagsContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/ProjectNameTest.java
  src/test/java/seedu/address/model/skill/SkillTest.java
  src/test/java/seedu/address/model/skill/SkillsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/TagsContainsKeywordsPredicateTest.java
Labels: type.Task

#110 Add skills to projects
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddProjectCommandParser.java
  src/main/java/seedu/address/model/project/Project.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/main/resources/view/ProjectListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddProjectCommandParserTest.java
  src/test/java/seedu/address/model/project/ProjectTest.java
  src/test/java/seedu/address/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/address/testutil/AssignmentBuilder.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: type.Task, priority.High

#130 Rename person fxml files to employee
  src/main/resources/view/EmployeeListCard.fxml
  src/main/resources/view/EmployeeListPanel.fxml
Labels: alpha-bug

#138 Fix employee fields overflow
  docs/UserGuide.md
  src/main/java/seedu/address/model/skill/Skill.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/resources/view/EmployeeListCard.fxml
  src/test/java/seedu/address/model/employee/EmployeeIdTest.java
  src/test/java/seedu/address/model/skill/SkillTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: alpha-bug

#139 Update listemployees ug
  docs/UserGuide.md
Labels: type.Task, severity.Medium
