Repository AY2425S1-CS2103T-T15-4/tp, pull requests merged in 2024-11, with the labels that each got.

#141 Fix spacing issue
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
Labels: alpha-bug

#155 Fix command 'listprojects' typo in user guide
  docs/UserGuide.md
Labels: type.Bug, severity.Low, alpha-bug

#156 Handle deletes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearProjectCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteProjectCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/UnassignCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/assignment/UniqueAssignmentListTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#162 Extract ids
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddProjectCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/AssignmentId.java
  src/main/java/seedu/address/model/employee/EmployeeId.java
  src/main/java/seedu/address/model/id/Id.java
  src/main/java/seedu/address/model/project/ProjectId.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedEmployee.java
  src/main/java/seedu/address/storage/JsonAdaptedProject.java
  src/main/java/seedu/address/ui/ProjectCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicateAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidAssignmentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidProjectAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAssignmentsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalProjectsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddProjectCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/assignment/AssignmentIdTest.java
  src/test/java/seedu/address/model/employee/EmployeeIdTest.java
  src/test/java/seedu/address/model/id/IdTest.java
  src/test/java/seedu/address/model/project/ProjectIdTest.java
  src/test/java/seedu/address/model/project/ProjectNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/project/UniqueProjectListTest.java
  src/test/java/seedu/address/testutil/ProjectBuilder.java
  src/test/java/seedu/address/testutil/ProjectUtil.java
  src/test/java/seedu/address/testutil/TypicalProjects.java
Labels: type.Task, type.Bug

#175 Listcommands msg
  src/main/java/seedu/address/logic/commands/listcommands/ListAssignmentsCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListEmployeesCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListProjectsCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/listcommands/ListAssignmentsCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommands/ListEmployeesCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommands/ListProjectsCommandTest.java
Labels: type.Enhancement

#164 Implement EditProjectCommand
  src/main/java/seedu/address/logic/commands/EditProjectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditProjectCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditProjectCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditProjectCommandParserTest.java
  src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
Labels: type.Task, priority.High

#182 Change addressbook.json to hrconnect.json
  docs/UserGuide.md
Labels: priority.Low, severity.Low, alpha-bug

#171 Update DG for 1.5
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.High

#169 Add assignments to sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task, priority.Medium

#165 Fix file paths do not match with new application name (HRConnect)
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.Bug, priority.Medium, alpha-bug

#187 Update DG Table of content Appendix: Requirement
  docs/DeveloperGuide.md
Labels: alpha-bug

#185 Update UG for editproject command
  docs/UserGuide.md
Labels: priority.High, alpha-bug

#178 Update listprojectmembers command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/listcommands/ListProjectMembersCommand.java
  src/main/java/seedu/address/logic/commands/listcommands/ListProjectsCommand.java
  src/main/java/seedu/address/logic/parser/ListProjectMembersCommandParser.java
  src/main/java/seedu/address/model/assignment/AssignmentProjectPredicate.java
  src/test/java/seedu/address/logic/parser/ListProjectMembersCommandParserTest.java
Labels: priority.Medium, alpha-bug

#180 Update UG for `listprojectmembers`
  docs/UserGuide.md
  src/main/java/seedu/address/model/assignment/AssignmentProjectPredicate.java
Labels: priority.High

#191 Fix UG Command Summary tables
  docs/UserGuide.md
Labels: type.Bug, priority.High

#195 Update app version
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#272 Fix reported UG bugs
  docs/UserGuide.md
  docs/images/uiExample.png
Labels: type.Task, priority.High

#280 Fix address slash
  docs/UserGuide.md
  src/main/java/seedu/address/model/employee/Address.java
  src/test/java/seedu/address/model/employee/AddressTest.java
Labels: type.Bug, severity.Medium

#276 Specify commands usage
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: type.Bug, priority.High

#284 Finalize UG
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/listAssignments.png
  docs/images/listEmployees.png
  docs/images/listProjects.png
Labels: type.Task, priority.High

#285 Add DG Planned Enhancements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#307 Update docs
  README.md
  docs/index.md
Labels: type.Task

#309 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#313 Update user stories to match features
  docs/DeveloperGuide.md
Labels: type.Task

#312 Add manual testing instruction of command history to dg
  docs/DeveloperGuide.md
Labels: type.Task, priority.High
